TDT.CAdmin/Controllers/MusicManagementController.cs
using Castle.Components.DictionaryAdapter.Xml;
using Google.Cloud.Firestore;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using TDT.Core.DTO;
using TDT.Core.DTO.Firestore;
using TDT.Core.Extensions;
using TDT.Core.Helper;
using TDT.Core.Ultils;
using TDT.Core.Ultils.MVCMessage;
using X.PagedList;

namespace TDT.CAdmin.Controllers
{
    public class MusicManagementController : Controller
    {
        public MusicManagementController()
        {
           
        }
        public bool IsIdInUse(string id)
        {
            SongDTO song = DataHelper.GetSong(id);
            if (song != null)
            {
                return true;
            }
            return false;
        }
        public IActionResult Index(string searchTerm, int? page)
        {
            ViewBag.SearchTerm = "";
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            List<SongDTO> lsong = null;
            int sobs = 0;
            if (string.IsNullOrEmpty(searchTerm))
            {
                Query query = FirestoreService.Instance.GetCollectionReference(FirestoreService.CL_Song).Offset((int)((pageNumber - 1) * pageSize)).Limit(pageSize);
                lsong = FirestoreService.Instance.Gets<SongDTO>(query);
                sobs = (int)FirestoreService.Instance.GetCollectionReference(FirestoreService.CL_Song).Count().GetSnapshotAsync().Result.Count;
                ViewBag.SoBH = sobs;
            }
            else if (DataHelper.Instance.Songs.Count > 0)
            {
                var _songs = DataHelper.Instance.Songs.Values.ToList();
                lsong = _songs.Where(r => r.title.ToLower().Contains(searchTerm.ToLower())).ToList();
                ViewBag.SoBH = lsong.Count;
                sobs = lsong.Count;
                lsong = _songs.Where(r => r.title.ToLower().Contains(searchTerm.ToLower())).Skip((int)((pageNumber - 1) * pageSize)).Take(pageSize).ToList();
                ViewBag.SearchTerm = searchTerm;
            }

            PageList<List<SongDTO>> pageList = new PageList<List<SongDTO>>(pageNumber, pageSize, sobs, lsong);
            return View(pageList);
        }
        [HttpGet]
        public string LoadImg(string encodeID, string thumbnail)
        {
            string img;
            if (DataHelper.Instance.ThumbSong.Keys.Contains(encodeID))
            {
                img = DataHelper.Instance.ThumbSong[encodeID];
            }
            else
            {
                img = FirebaseService.Instance.getStorage(thumbnail);
                DataHelper.Instance.ThumbSong.Add(encodeID, img);
            }
            return img;
        }
        public SelectList SelectListPlayList(int sokitu)
        {
            if (DataHelper.Instance.Playlists.Count > 0)
            {
                List<PlaylistDTO> albums = DataHelper.Instance.Playlists.Values.ToList();
                int maxCharacters = sokitu;
                foreach (var album in albums)
                {
                    if (album.title.Length > maxCharacters)
                    {
                        album.title = album.title.Substring(0, maxCharacters); // Giới hạn ký tự
                    }
                }

               return new SelectList(albums, "encodeId", "title");
            }
            return null;
        }
        public IActionResult Create()
        {
            ViewBag.Albums = SelectListPlayList(50);
            return View();
        }
        [HttpPost]
        public IActionResult Create(SongDTO songdto, IFormFile uploadFile)
        {
            ViewBag.Albums = SelectListPlayList(50);
            try
            {
                if(uploadFile == null)
                {
                    ViewBag.File = "Vui lòng chọn file ảnh";
                    return View();
                }
                string id = string.Empty;
                do
                {
                    id = HelperUtility.GenerateRandomString(8);

                } while (IsIdInUse(id));
                songdto.encodeId = id;
                Stream image = uploadFile.OpenReadStream();
                string thumbnail = id + "_" + DateTime.Now.ToString("yyyyMMddHHmmssfff").Replace("/", "_") + "." + uploadFile.FileName.Split('.').Last();
                string url = FirebaseService.Instance.pushFile(image, "Images/Song/0/" + thumbnail).Result;
                DataHelper.Instance.ThumbSong.Add(id, url);
                FirebaseService.Instance.pushFile(image, "Images/Song/1/" + thumbnail).Wait();
                songdto.thumbnail = "Images/Song/0/" + thumbnail;
                songdto.thumbnailM = "Images/Song/1/" + thumbnail;

                SongDTO Songfile = APICallHelper.Post<SongDTO>(
                   $"Song/InsertOrUpdate",
                   token: HttpContext.User.Claims.FirstOrDefault(c => c.Type.Equals("token")).Value,
                   requestBody: JsonConvert.SerializeObject(songdto)
               ).Result;

                if (Songfile.Code == Core.Enums.APIStatusCode.ActionSucceeded)
                {
                    //FlashMessage để truyền message từ đây sang action hoặc controller khác
                    this.MessageContainer().AddFlashMessage("Tạo bài hát thành công!", ToastMessageType.Success);
                    if (DataHelper.Instance.Songs.ContainsKey(songdto.encodeId))
                    {
                        DataHelper.Instance.Songs[songdto.encodeId] = songdto;
                    }
                    else
                    {
                        DataHelper.Instance.Songs.Add(songdto.encodeId, songdto);
                    }
                }
                else
                {
                    //Truyền message trong nội bộ hàm
                    this.MessageContainer().AddMessage(Songfile.Msg, ToastMessageType.Error);
                    return View();
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
        public IActionResult Edit(string id)
        {
            ViewBag.Albums = SelectListPlayList(50);
            SongDTO song = new SongDTO();
            Query query = FirestoreService.Instance.GetCollectionReference(FirestoreService.CL_Song).WhereEqualTo("encodeId", id);
            List<SongDTO> lsong = FirestoreService.Instance.Gets<SongDTO>(query);
            if (lsong != null)
            {
                song = lsong[0];
                return View(song);
            }
            return View();
        }
        [HttpPost]
        public IActionResult Edit(SongDTO song, IFormFile uploadFile)
        {
            try
            {
                if (uploadFile != null)
                {
                    Stream image = uploadFile.OpenReadStream();
                    string thumbnail = song.encodeId + "_" + DateTime.Now.ToString("yyyyMMddHHmmssfff").Replace("/", "_") + "." + uploadFile.FileName.Split('.').Last();
                    string url = FirebaseService.Instance.pushFile(image, "Images/Song/0/" + thumbnail).Result;
                    DataHelper.Instance.ThumbSong.Remove(song.encodeId);
                    DataHelper.Instance.ThumbSong.Add(song.encodeId, url);
                    FirebaseService.Instance.pushFile(image, "Images/Song/1/" + thumbnail).Wait();
                    song.thumbnail = "Images/Song/0/" + thumbnail;
                    song.thumbnailM = "Images/Song/1/" + thumbnail;
                }
                SongDTO Songfile = APICallHelper.Post<SongDTO>(
                $"Song/InsertOrUpdate",
                token: HttpContext.User.Claims.FirstOrDefault(c => c.Type.Equals("token")).Value,
                requestBody: JsonConvert.SerializeObject(song)
                ).Result;

                if (Songfile.Code == Core.Enums.APIStatusCode.ActionSucceeded)
                {
                    //FlashMessage để truyền message từ đây sang action hoặc controller khác
                    this.MessageContainer().AddFlashMessage("Sửa hát thành công!", ToastMessageType.Success);
                    if(DataHelper.Instance.Songs.ContainsKey(song.encodeId))
                    {
                        DataHelper.Instance.Songs[song.encodeId] = song;
                    }
                    else
                    {
                        DataHelper.Instance.Songs.Add(song.encodeId, song);
                    }
                }
                else
                {
                    //Truyền message trong nội bộ hàm
                    this.MessageContainer().AddMessage(Songfile.Msg, ToastMessageType.Error);
                    return View();
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        [HttpPost]
        public IActionResult Delete(string id)
        {
            ResponseDataDTO<SongDTO> songDTO = APICallHelper.Delete<ResponseDataDTO<SongDTO>>($"Song/{id}", token: HttpContext.User.Claims.FirstOrDefault(c => c.Type.Equals("token")).Value).Result;
            if (songDTO.Code == Core.Enums.APIStatusCode.ActionSucceeded)
            {
                this.MessageContainer().AddFlashMessage("Xóa bài hát thành công!", ToastMessageType.Success);
                if(DataHelper.Instance.Songs.ContainsKey(id))
                {
                    DataHelper.Instance.Songs.Remove(id);
                }
            }
            else
            {
                this.MessageContainer().AddFlashMessage(songDTO.Msg, ToastMessageType.Error);
            }
            return new JsonResult("ok");
        }
        public IActionResult Details(string id)
        {
            SongDTO song = DataHelper.GetSong(id);
            if (song != null)
            {

TDT.CAdmin/Views/MusicManagement/Delete.cshtml
@model TDT.Core.DTO.Firestore.SongDTO

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="title-admin">Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SongDTO</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.encodeId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.encodeId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.alias)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.alias)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.isOffical)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.isOffical)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.username)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.username)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.artistsNames)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.artistsNames)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.isWorldWide)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.isWorldWide)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.thumbnailM)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.thumbnailM)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.link)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.link)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.thumbnail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.thumbnail)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.duration)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.duration)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.zingChoice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.zingChoice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.isPrivate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.isPrivate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.preRelease)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.preRelease)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.releaseDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.releaseDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.distributor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.distributor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.isIndie)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.isIndie)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.streamingStatus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.streamingStatus)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.allowAudioAds)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.allowAudioAds)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.hasLyric)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.hasLyric)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.userid)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.userid)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.album)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.album)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.isRBT)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.isRBT)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.like)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.like)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.listen)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.listen)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.liked)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.liked)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.comment)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.comment)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Code)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Code)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Msg)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Msg)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Trở về trang trước</a>
    </form>
</div>

TDT.CAdmin/Views/MusicManagement/Index.cshtml
@using TDT.Core.DTO.Firestore;
@using TDT.Core.Helper;
@model PageList<List<SongDTO>>

@{
    ViewData["Title"] = "Danh sách bài hát";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2 class="title-admin">Danh sách bài hát</h2>

@{
    int maxLength = 20; // Đặt giá trị tối đa
}
<div class="row">
    <div class="col-3">
        <a type="button" class="btn btn-outline-dark" asp-action="Create">Tạo Bài Hát Mới</a>
    </div>
    <div class="col-6">
        @{
            if (ViewBag.SearchTerm != "")
            {
                            <p>Số bài hát tìm được: @ViewBag.SoBH</p>
            }
        }
    </div>
    <div class="col-3 input-group mb-3 ">
        <input type="text" class="form-control border" placeholder="Nhập vào bài hát cần tìm"
               aria-label="Nhập vào bài hát cần tìm" aria-describedby="button-search"
               id="searchTerm" value="@ViewBag.SearchTerm">
        <div class="input-group-append">
            <button class="btn btn-outline-dark" type="button" id="button-search">
                <i class="fa fa-search" aria-hidden="true"></i>
            </button>
        </div>
    </div>
</div>

<div class="table-container">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Mã ID</th>
                <th>Tiêu Đề</th>
                <th>Tên nghệ sĩ</th>
                <th>Ảnh</th>
                <th>Bản riêng tư</th>
                <th>Nhà phát hành</th>
                <th></th>
            </tr>
        </thead>
        <tbody>

            @foreach (var item in Model.Items)
            {
                <tr>
                    <td scope="row">
                        @Html.DisplayFor(modelItem => item.encodeId)
                    </td>
                    <td>
                        @{
                            string truncatedTitle = item.title.Length > maxLength ? item.title.Substring(0, maxLength) + "..." : item.title;
                        }
                        @truncatedTitle
                    </td>
                    <td>
                        @{
                            string truncatedArtistsNames = item.artistsNames.Length > maxLength ? item.artistsNames.Substring(0, maxLength) + "..." : item.artistsNames;
                        }
                        @truncatedArtistsNames
                    </td>
                    <td class="img_song" encodeid="@item.encodeId" thumbnail="@item.thumbnail">
                    </td>
                    <td>
                        @item.ReleaseDate()
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.distributor)
                    </td>
                    <td class="btn-control">
                        <a title="Chi tiết" href="@Url.Action("Details", "MusicManagement", new { id = item.encodeId})">
                            <div class="fa fa-eye" aria-hidden="true">
                            </div>
                        </a>
                        <a title="Cập nhật thông tin" href="@Url.Action("Edit", "MusicManagement", new { id = item.encodeId})">
                            <div class="fa" aria-hidden="true">
                                <svg style="fill: #ffbc0a;" xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 512 512">
                                    <path d="M362.7 19.3L314.3 67.7 444.3 197.7l48.4-48.4c25-25 25-65.5 0-90.5L453.3 19.3c-25-25-65.5-25-90.5 0zm-71 71L58.6 323.5c-10.4 10.4-18 23.3-22.2 37.4L1 481.2C-1.5 489.7 .8 498.8 7 505s15.3 8.5 23.7 6.1l120.3-35.4c14.1-4.2 27-11.8 37.4-22.2L421.7 220.3 291.7 90.3z" />
                                </svg>
                            </div>
                        </a>
                        <a title="Xóa" onclick="DVNConfirm('Xóa', 'Bài Hát' , '/MusicManagement/Delete' , '@item.encodeId')">
                             <div class="fa" aria-hidden="true">
                                <svg style="fill: #fc424a" xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 448 512">
                                    <path d="M135.2 17.7L128 32H32C14.3 32 0 46.3 0 64S14.3 96 32 96H416c17.7 0 32-14.3 32-32s-14.3-32-32-32H320l-7.2-14.3C307.4 6.8 296.3 0 284.2 0H163.8c-12.1 0-23.2 6.8-28.6 17.7zM416 128H32L53.2 467c1.6 25.3 22.6 45 47.9 45H346.9c25.3 0 46.3-19.7 47.9-45L416 128z" />
                                </svg>
                            </div>
                        </a>
                     
                    </td>

                </tr>
            }
        </tbody>
    </table>
</div>

<!-- Hiển thị điều hướng phân trang -->
<div class="pagination">
    <ul>
        @{
            int soquaylai = Model.PageNumber - 1;
            int sotienlen = Model.PageNumber + 1;
            string sr = ViewBag.SearchTerm;
        }
        @if (Model.PageNumber > 1)
        {
            <li><a asp-action="Index" asp-route-page="" asp-route-searchTerm="@sr"><i class="fa fa-angle-double-left" aria-hidden="true"></i></a></li>

            <li><a asp-action="Index" asp-route-page="@soquaylai" asp-route-searchTerm="@sr"><i class="fa fa-angle-left" aria-hidden="true"></i></a></li>
            @if (Model.PageNumber > 4)
            {
                <li><span>...</span></li>
            }
            @for (var i = Model.PageNumber - 3; i < Model.PageNumber; i++)
            {
                if (i > 0)
                {
                    <li><a asp-action="Index" asp-route-page="@i" asp-route-searchTerm="@sr">@i</a></li>
                }
            }
        }
        <li class="active"><a>@Model.PageNumber</a></li>
        @for (var i = Model.PageNumber + 1; i <= Model.PageNumber + 3; i++)
        {
            if (i <= Model.TotalPages)
            {
                <li><a asp-action="Index" asp-route-page="@i" asp-route-searchTerm="@sr">@i </a></li>
            }
        }
        @if (Model.PageNumber < Model.TotalPages)
        {
            @if (Model.PageNumber < Model.TotalPages - 3)
            {
                <li><span>...</span></li>
            }
            <li><a asp-action="Index" asp-route-page="@sotienlen" asp-route-searchTerm="@sr"><i class="fa fa-angle-right" aria-hidden="true"></i></a></li>
            <li><a asp-action="Index" asp-route-page="@Model.TotalPages" asp-route-searchTerm="@sr"><i class="fa fa-angle-double-right" aria-hidden="true"></i></a></li>

        }
    </ul>
    <div style="margin-left: auto; align-items: self-end !important;">
        Đến Trang
        <input type="text" id="pageInput" name="pageInput" style="width: 60px;"> / @Model.TotalPages
        <div class="btn" id="goToPageButton">Đến</div>
    </div>
</div>

<script>
    $(".img_song").each(function (e, val) {
        var id = $(this).attr("encodeid");
        var thumbnail = $(this).attr("thumbnail");
        loadImg(this, id, thumbnail);
        console.log(id, thumbnail);

    })
    function loadImg(that, _id, _thumbnail) {
        $.ajax({
            url: "/MusicManagement/LoadImg",
            data: {
                encodeID: _id,
                thumbnail: _thumbnail
            },
            success: function (data) {
                // $('#img_song').html(data);
                $(that).html('<img src="' + data + '"/>');
            }
        });
    }
    $(document).ready(function () {
        $('#button-search').click(function () {
            var searchTerm = $('#searchTerm').val();
            window.location.href = '@Url.Action("Index", new { page = 1})' + '&searchTerm=' + searchTerm;
        });
        $('#searchTerm').keypress(function (e) {
            var key = e.which;
            if (key == 13) {
                var searchTerm = $('#searchTerm').val();
                window.location.href = '@Url.Action("Index", new { page =  1})' + '&searchTerm=' + searchTerm;
            }
        });
        $('#goToPageButton').click(function (e) {
            e.preventDefault();
            var pageInput = $('#pageInput').val();
            var maxpage = @Model.TotalPages;
            var searchTerm = $('#searchTerm').val(); 

            if (pageInput && !isNaN(pageInput) && pageInput > 0) {
                if (pageInput > maxpage) {
                    pageInput = maxpage;
                }
                var url = "/MusicManagement?page=" + pageInput;

                if (searchTerm) {
                    url += "&searchTerm=" + encodeURIComponent(searchTerm);
                }

                window.location.href = url;
            }
        });


    });
</script>